import 'models.dart';
import 'theme.dart';

final List<Category> kCategories = [
  Category(
    id: 'cellular',
    name: 'סלולר',
    sub: 'מנויים ניידים',
    icon: '📱',
    currentBill: 119,
    color: AppColors.green,
  ),
  Category(
    id: 'internet',
    name: 'אינטרנט',
    sub: 'סיב אופטי וכבלים',
    icon: '🌐',
    currentBill: 140,
    color: AppColors.greenLight,
  ),
  Category(
    id: 'tv',
    name: 'טלוויזיה',
    sub: 'שידור וסטרימינג',
    icon: '📺',
    currentBill: 130,
    color: AppColors.orange,
  ),
  Category(
    id: 'triple',
    name: 'חבילה משולבת',
    sub: 'אינטרנט + טלוויזיה + טלפון',
    icon: '🏠',
    currentBill: 260,
    color: AppColors.blueLight,
  ),
  Category(
    id: 'abroad',
    name: "חו\"ל",
    sub: 'שיחות ונתונים בחו"ל',
    icon: '✈️',
    currentBill: 0,
    color: AppColors.warn,
  ),
];

final List<Plan> kPlans = [
  // ── CELLULAR ──────────────────────────────────────────────────
  Plan(
    id: 'c-019',
    cat: 'cellular',
    provider: '019 מובייל',
    net: 'LTE',
    plan: '12GB ללא הגבלה',
    price: 19.90,
    rating: 3.8,
    reviews: 214,
    flags: ['nocommit', 'fixed'],
    feats: [
      PlanFeat('📶', '12GB גלישה'),
      PlanFeat('📞', 'שיחות ללא הגבלה'),
      PlanFeat('✉️', 'SMS ללא הגבלה'),
      PlanFeat('🔒', 'מחיר קבוע לתמיד'),
    ],
    fine: 'מחיר אינו כולל מע"מ',
  ),
  Plan(
    id: 'c-partner-20',
    cat: 'cellular',
    provider: 'פרטנר',
    net: '5G',
    plan: '20GB 5G',
    price: 29,
    rating: 4.1,
    reviews: 381,
    flags: ['5g', 'nocommit'],
    feats: [
      PlanFeat('📶', '20GB גלישה'),
      PlanFeat('📡', '5G מהיר'),
      PlanFeat('📞', 'שיחות ללא הגבלה'),
      PlanFeat('🔓', 'ללא התחייבות'),
    ],
  ),
  Plan(
    id: 'c-golan-50',
    cat: 'cellular',
    provider: 'גולן טלקום',
    net: '5G',
    plan: '50GB 5G',
    price: 39,
    after: 49,
    intro: '3 חודשים ראשונים',
    rating: 4.3,
    reviews: 1053,
    flags: ['5g', 'nocommit'],
    best: true,
    feats: [
      PlanFeat('📶', '50GB גלישה'),
      PlanFeat('📡', '5G מהיר'),
      PlanFeat('📞', 'שיחות ללא הגבלה'),
      PlanFeat('🌍', 'רואמינג בסיסי'),
      PlanFeat('🔓', 'ללא התחייבות'),
    ],
    fine: 'לאחר 3 חודשים המחיר עולה ל-₪49',
  ),
  Plan(
    id: 'c-hot-100',
    cat: 'cellular',
    provider: 'הוט מובייל',
    net: '5G',
    plan: '100GB 5G',
    price: 49,
    rating: 4.0,
    reviews: 729,
    flags: ['5g', 'nocommit'],
    feats: [
      PlanFeat('📶', '100GB גלישה'),
      PlanFeat('📡', '5G מהיר'),
      PlanFeat('📞', 'שיחות ללא הגבלה'),
      PlanFeat('🔓', 'ללא התחייבות'),
    ],
  ),
  Plan(
    id: 'c-cellcom-200',
    cat: 'cellular',
    provider: 'סלקום',
    net: '5G',
    plan: '200GB 5G',
    price: 59,
    rating: 4.2,
    reviews: 892,
    flags: ['5g', 'nocommit'],
    feats: [
      PlanFeat('📶', '200GB גלישה'),
      PlanFeat('📡', '5G מהיר'),
      PlanFeat('📞', 'שיחות ללא הגבלה'),
      PlanFeat('🔒', 'ביטוח מכשיר'),
      PlanFeat('🔓', 'ללא התחייבות'),
    ],
  ),
  Plan(
    id: 'c-partner-500',
    cat: 'cellular',
    provider: 'פרטנר',
    net: '5G',
    plan: '500GB 5G + חו"ל',
    price: 69,
    rating: 4.4,
    reviews: 567,
    flags: ['5g', 'nocommit', 'abroad'],
    feats: [
      PlanFeat('📶', '500GB גלישה'),
      PlanFeat('📡', '5G מהיר'),
      PlanFeat('📞', 'שיחות ללא הגבלה'),
      PlanFeat('✈️', 'גלישה בחו"ל 5GB/חודש'),
      PlanFeat('🔓', 'ללא התחייבות'),
    ],
  ),
  Plan(
    id: 'c-pelephone-1000',
    cat: 'cellular',
    provider: 'פלאפון',
    net: '5G',
    plan: '1000GB 5G פרימיום',
    price: 75,
    after: 95,
    term: '24',
    intro: '12 חודשים ראשונים',
    rating: 4.1,
    reviews: 445,
    flags: ['5g'],
    feats: [
      PlanFeat('📶', '1000GB גלישה'),
      PlanFeat('📡', '5G Ultra'),
      PlanFeat('📞', 'שיחות ללא הגבלה'),
      PlanFeat('✈️', 'גלישה בחו"ל 10GB/חודש'),
      PlanFeat('📺', 'שנה HOT NOW חינם'),
    ],
    fine: 'התחייבות 24 חודש, לאחר 12 חודש: ₪95',
  ),
  Plan(
    id: 'c-rami-levi',
    cat: 'cellular',
    provider: 'רמי לוי',
    net: 'LTE',
    plan: 'ללא הגבלה LTE',
    price: 30,
    rating: 3.9,
    reviews: 310,
    flags: ['nocommit'],
    feats: [
      PlanFeat('📶', 'גלישה ללא הגבלה'),
      PlanFeat('📞', 'שיחות ללא הגבלה'),
      PlanFeat('✉️', 'SMS ללא הגבלה'),
      PlanFeat('🔓', 'ללא התחייבות'),
    ],
  ),
  Plan(
    id: 'c-pelephone-fam',
    cat: 'cellular',
    provider: 'פלאפון',
    net: '5G',
    plan: 'חבילת משפחה 4 קווים',
    price: 49,
    after: 60,
    term: '24',
    intro: '6 חודשים ראשונים',
    rating: 4.0,
    reviews: 298,
    flags: ['5g', 'family'],
    feats: [
      PlanFeat('👨‍👩‍👧‍👦', '4 קווים יחד'),
      PlanFeat('📶', '100GB לכל קו'),
      PlanFeat('📡', '5G מהיר'),
      PlanFeat('📞', 'שיחות בין הקווים חינם'),
    ],
    fine: 'חבילת משפחה, 4 קווים במחיר ₪49/קו',
  ),

  // ── INTERNET ──────────────────────────────────────────────────
  Plan(
    id: 'i-bezeq-200',
    cat: 'internet',
    provider: 'בזק',
    net: 'סיב אופטי',
    plan: '200Mbps סיב אופטי',
    price: 99,
    rating: 4.0,
    reviews: 1203,
    flags: ['fiber'],
    feats: [
      PlanFeat('⚡', '200Mbps הורדה'),
      PlanFeat('⬆️', '20Mbps העלאה'),
      PlanFeat('📦', 'ראוטר חינם'),
      PlanFeat('🛠', 'טכנאי לבית חינם'),
    ],
    fine: 'כולל התקנה',
  ),
  Plan(
    id: 'i-hot-500',
    cat: 'internet',
    provider: 'הוט',
    net: 'כבל',
    plan: '500Mbps כבל',
    price: 109,
    rating: 3.9,
    reviews: 987,
    flags: [],
    feats: [
      PlanFeat('⚡', '500Mbps הורדה'),
      PlanFeat('⬆️', '50Mbps העלאה'),
      PlanFeat('📦', 'מודם חינם'),
      PlanFeat('📺', 'ניתן לצרף טלוויזיה'),
    ],
  ),
  Plan(
    id: 'i-partner-1000',
    cat: 'internet',
    provider: 'פרטנר',
    net: 'סיב אופטי',
    plan: '1000Mbps גיגה סיב',
    price: 119,
    rating: 4.3,
    reviews: 752,
    flags: ['fiber', 'best'],
    best: true,
    feats: [
      PlanFeat('⚡', '1000Mbps הורדה'),
      PlanFeat('⬆️', '100Mbps העלאה'),
      PlanFeat('📦', 'ראוטר WiFi 6'),
      PlanFeat('🛠', 'התקנה מקצועית'),
      PlanFeat('📞', 'טלפון בית חינם שנה'),
    ],
  ),
  Plan(
    id: 'i-cellcom-1000',
    cat: 'internet',
    provider: 'סלקום',
    net: 'סיב אופטי',
    plan: '1000Mbps סיב',
    price: 109,
    rating: 4.1,
    reviews: 631,
    flags: ['fiber'],
    feats: [
      PlanFeat('⚡', '1000Mbps הורדה'),
      PlanFeat('⬆️', '100Mbps העלאה'),
      PlanFeat('📦', 'ראוטר חינם'),
      PlanFeat('🔓', 'ללא התחייבות'),
    ],
  ),
  Plan(
    id: 'i-gilat-50',
    cat: 'internet',
    provider: 'גילת',
    net: 'לווין',
    plan: 'לווין 50Mbps',
    price: 129,
    rating: 3.5,
    reviews: 198,
    flags: ['satellite'],
    feats: [
      PlanFeat('🛰', 'כיסוי לכל הארץ'),
      PlanFeat('⚡', '50Mbps הורדה'),
      PlanFeat('⬆️', '10Mbps העלאה'),
      PlanFeat('🏘', 'מתאים ליישובים מרוחקים'),
    ],
    fine: 'כולל ציוד לווין, דורש התקנה',
  ),
  Plan(
    id: 'i-bezeq-1000',
    cat: 'internet',
    provider: 'בזק',
    net: 'סיב אופטי',
    plan: '1000Mbps גיגה פרימיום',
    price: 139,
    rating: 4.2,
    reviews: 843,
    flags: ['fiber'],
    feats: [
      PlanFeat('⚡', '1000Mbps הורדה'),
      PlanFeat('⬆️', '100Mbps העלאה'),
      PlanFeat('📦', 'ראוטר WiFi 6E'),
      PlanFeat('🛠', 'תמיכה עדיפות'),
    ],
  ),

  // ── TV ────────────────────────────────────────────────────────
  Plan(
    id: 'tv-freetv',
    cat: 'tv',
    provider: 'FreeTV',
    net: 'סטרימינג',
    plan: 'בייסיק סטרימינג',
    price: 29,
    rating: 3.7,
    reviews: 312,
    flags: ['streaming'],
    feats: [
      PlanFeat('📺', '40+ ערוצים חינם'),
      PlanFeat('📱', 'אפליקציה לכל מכשיר'),
      PlanFeat('⏺', 'הקלטה ב-DVR'),
      PlanFeat('🔓', 'ללא התחייבות'),
    ],
  ),
  Plan(
    id: 'tv-hot',
    cat: 'tv',
    provider: 'הוט',
    net: 'כבל',
    plan: 'HOT 70+ ערוצים',
    price: 79,
    rating: 3.9,
    reviews: 1567,
    flags: ['cable'],
    feats: [
      PlanFeat('📺', '70+ ערוצים'),
      PlanFeat('📦', 'ממיר מתנה'),
      PlanFeat('⏺', 'DVR 500GB'),
      PlanFeat('🎬', 'HOT NOW כלול'),
    ],
  ),
  Plan(
    id: 'tv-partner',
    cat: 'tv',
    provider: 'פרטנר TV',
    net: 'סטרימינג',
    plan: '100+ ערוצים + VOD',
    price: 89,
    rating: 4.1,
    reviews: 734,
    flags: ['streaming', 'vod'],
    best: true,
    feats: [
      PlanFeat('📺', '100+ ערוצים'),
      PlanFeat('🎬', 'ספריית VOD ענקית'),
      PlanFeat('📱', 'עד 4 מסכים בו-זמנית'),
      PlanFeat('🔓', 'ללא התחייבות'),
    ],
  ),
  Plan(
    id: 'tv-yes',
    cat: 'tv',
    provider: 'yes',
    net: 'לווין',
    plan: 'yes פלטינום 140+ ערוצים',
    price: 149,
    rating: 4.3,
    reviews: 2103,
    flags: ['satellite', 'premium'],
    feats: [
      PlanFeat('📺', '140+ ערוצים'),
      PlanFeat('🎬', 'yes VOD כלול'),
      PlanFeat('🌍', 'ערוצי חו"ל פרימיום'),
      PlanFeat('⏺', 'DVR 1TB'),
      PlanFeat('📦', 'ממיר 4K'),
    ],
    fine: 'התקנת לווין נדרשת',
  ),
  Plan(
    id: 'tv-cellcom',
    cat: 'tv',
    provider: 'סלקום TV',
    net: 'סטרימינג',
    plan: 'סטרימינג + כבלים',
    price: 99,
    rating: 4.0,
    reviews: 521,
    flags: ['streaming', 'cable'],
    feats: [
      PlanFeat('📺', '80+ ערוצים'),
      PlanFeat('🎬', 'VOD ו-VOD פרימיום'),
      PlanFeat('📱', 'עד 3 מסכים'),
      PlanFeat('🔓', 'ללא התחייבות'),
    ],
  ),

  // ── TRIPLE ────────────────────────────────────────────────────
  Plan(
    id: 'tr-hot',
    cat: 'triple',
    provider: 'הוט',
    net: 'כבל',
    plan: 'סיב 500Mb + TV + טלפון',
    price: 149,
    rating: 4.0,
    reviews: 892,
    flags: ['bundle'],
    feats: [
      PlanFeat('🌐', '500Mbps אינטרנט'),
      PlanFeat('📺', '70+ ערוצי HOT'),
      PlanFeat('📞', 'טלפון בית ללא הגבלה'),
      PlanFeat('💰', 'חיסכון ₪40/חודש לעומת נפרד'),
    ],
    best: true,
  ),
  Plan(
    id: 'tr-partner',
    cat: 'triple',
    provider: 'פרטנר',
    net: 'סיב אופטי',
    plan: 'גיגה + TV + טלפון',
    price: 169,
    rating: 4.2,
    reviews: 743,
    flags: ['bundle', 'fiber'],
    feats: [
      PlanFeat('🌐', '1000Mbps גיגה סיב'),
      PlanFeat('📺', '100+ ערוצים'),
      PlanFeat('📞', 'טלפון בית ו-10GB נייד'),
      PlanFeat('💰', 'חיסכון ₪60/חודש לעומת נפרד'),
    ],
  ),
  Plan(
    id: 'tr-cellcom',
    cat: 'triple',
    provider: 'סלקום',
    net: 'סיב אופטי',
    plan: 'גיגה + TV + טלפון',
    price: 179,
    rating: 4.1,
    reviews: 521,
    flags: ['bundle', 'fiber'],
    feats: [
      PlanFeat('🌐', '1000Mbps גיגה סיב'),
      PlanFeat('📺', '80+ ערוצים'),
      PlanFeat('📞', 'טלפון בית ו-20GB נייד'),
      PlanFeat('💰', 'חיסכון ₪50/חודש לעומת נפרד'),
    ],
  ),
  Plan(
    id: 'tr-yes',
    cat: 'triple',
    provider: 'yes',
    net: 'לווין + סיב',
    plan: 'לווין + סיב גיגה + טלפון',
    price: 199,
    rating: 4.3,
    reviews: 1043,
    flags: ['bundle', 'satellite', 'fiber'],
    feats: [
      PlanFeat('🌐', '1000Mbps סיב'),
      PlanFeat('📺', '140+ ערוצי yes פלטינום'),
      PlanFeat('📞', 'טלפון בית ו-30GB נייד'),
      PlanFeat('💰', 'חיסכון ₪80/חודש לעומת נפרד'),
    ],
  ),
  Plan(
    id: 'tr-sting',
    cat: 'triple',
    provider: 'NEXT TV',
    net: 'סיב אופטי',
    plan: 'STING+ דאבל חבילה',
    price: 149,
    rating: 3.8,
    reviews: 234,
    flags: ['bundle'],
    feats: [
      PlanFeat('🌐', '500Mbps אינטרנט'),
      PlanFeat('📺', '60+ ערוצים'),
      PlanFeat('💰', 'מחיר קבוע 3 שנים'),
      PlanFeat('🔓', 'ללא התחייבות'),
    ],
  ),

  // ── ABROAD ────────────────────────────────────────────────────
  Plan(
    id: 'ab-019',
    cat: 'abroad',
    provider: '019 מובייל',
    net: 'רואמינג',
    plan: 'תעריף שיחות ₪0.99/דקה',
    priceText: '₪0.99/דקה',
    price: 0.99,
    rating: 3.6,
    reviews: 187,
    flags: ['permin'],
    feats: [
      PlanFeat('📞', '₪0.99/דקה לחו"ל'),
      PlanFeat('📱', 'ללא חבילה חודשית'),
      PlanFeat('🌍', 'כיסוי 100+ מדינות'),
      PlanFeat('✉️', 'SMS ₪0.29'),
    ],
  ),
  Plan(
    id: 'ab-golan-eu',
    cat: 'abroad',
    provider: 'גולן טלקום',
    net: '4G',
    plan: 'יורופה ₪9.90/יום',
    priceText: '₪9.90/יום',
    price: 9.90,
    rating: 4.2,
    reviews: 432,
    flags: ['perday', 'europe'],
    feats: [
      PlanFeat('🇪🇺', 'כל מדינות אירופה'),
      PlanFeat('📶', 'גלישה ללא הגבלה'),
      PlanFeat('📞', 'שיחות כלולות'),
      PlanFeat('📱', 'מחיר ליום, לא לחודש'),
    ],
    best: true,
  ),
  Plan(
    id: 'ab-partner-world',
    cat: 'abroad',
    provider: 'פרטנר',
    net: '4G',
    plan: 'עולמי 1GB ₪29/חודש',
    price: 29,
    rating: 4.0,
    reviews: 312,
    flags: ['monthly', 'worldwide'],
    feats: [
      PlanFeat('🌍', '180+ מדינות'),
      PlanFeat('📶', '1GB גלישה'),
      PlanFeat('📞', 'שיחות ₪1.5/דקה'),
      PlanFeat('✉️', 'SMS ₪0.50'),
    ],
  ),
  Plan(
    id: 'ab-pelephone-5',
    cat: 'abroad',
    provider: 'פלאפון',
    net: '4G',
    plan: 'עולמי 5GB ₪49/חודש',
    price: 49,
    rating: 4.1,
    reviews: 267,
    flags: ['monthly', 'worldwide'],
    feats: [
      PlanFeat('🌍', '200+ מדינות'),
      PlanFeat('📶', '5GB גלישה'),
      PlanFeat('📞', 'שיחות כלולות 100 דקות'),
      PlanFeat('✉️', 'SMS ללא הגבלה'),
      PlanFeat('📱', 'eSIM נתמך'),
    ],
  ),
  Plan(
    id: 'ab-airalo-esim',
    cat: 'abroad',
    provider: 'Airalo',
    net: 'eSIM',
    plan: 'eSIM יורופה 3GB',
    price: 12,
    rating: 4.4,
    reviews: 789,
    flags: ['esim', 'europe'],
    feats: [
      PlanFeat('📱', 'eSIM דיגיטלי מיידי'),
      PlanFeat('📶', '3GB ב-30 יום'),
      PlanFeat('🇪🇺', '35 מדינות אירופה'),
      PlanFeat('⚡', 'הפעלה מיידית'),
    ],
  ),
];

List<Plan> plansByCategory(String catId) =>
    kPlans.where((p) => p.cat == catId).toList();

Plan? planById(String id) {
  try {
    return kPlans.firstWhere((p) => p.id == id);
  } catch (_) {
    return null;
  }
}

Category? categoryById(String id) {
  try {
    return kCategories.firstWhere((c) => c.id == id);
  } catch (_) {
    return null;
  }
}
