-- ─────────────────────────────────────────────────────────────────────────────
-- Full plans seed — GENERATED from lib/data.dart seedPlans.
-- Regenerate with:  flutter test tool/gen_plans_seed.dart
-- Do not edit by hand; edit the catalogue and regenerate.
-- Plans: 120
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.plans
  (id, provider, category, price, price_exact, title, specs, kind, price_unit, fees, rating, review_count, is_featured)
values
  ('cel_cellcom_5gprocare1500', 'סלקום', 'cellular', 70, 69.9, '5G Pro Care 1500GB', '{"נתונים":"1500GB","דקות":"500 דק׳","SMS":"5,000"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"אין"}'::jsonb, 4.2, 0, false),
  ('cel_cellcom_4gbasic500', 'סלקום', 'cellular', 45, 44.9, '4G Basic 500GB', '{"נתונים":"500GB","דקות":"150 דק׳","SMS":"3,500"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"אין"}'::jsonb, 4.1, 0, false),
  ('cel_cellcom_5g800', 'סלקום', 'cellular', 40, 39.9, '5G 800GB', '{"נתונים":"800GB","דקות":"500 דק׳","SMS":"5,000"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"אין"}'::jsonb, 4.2, 0, false),
  ('cel_cellcom_5gpro1000', 'סלקום', 'cellular', 60, 59.9, '5G Pro 1000GB', '{"נתונים":"1000GB","דקות":"500 דק׳","SMS":"5,000"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"אין"}'::jsonb, 4.0, 0, false),
  ('cel_cellcom_5gprofly1500', 'סלקום', 'cellular', 120, 119.9, '5G Pro Fly 1500GB', '{"נתונים":"1500GB","דקות":"500 דק׳","SMS":"5,000","חו\"ל":"5GB + 50 דק׳/SMS לחודש"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"אין"}'::jsonb, 3.8, 0, false),
  ('cel_partner_prince400', 'פרטנר', 'cellular', 35, 34.9, 'Prince 400GB', '{"נתונים":"400GB","דקות":"200 דק׳","SMS":"3,500","חו\"ל":"200 דק׳ ל-42 יעדים"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"אין"}'::jsonb, 4.2, 0, false),
  ('cel_partner_queen5g500', 'פרטנר', 'cellular', 40, 39.9, 'Queen 5G 500GB', '{"נתונים":"500GB","דקות":"400 דק׳","SMS":"5,000","חו\"ל":"400 דק׳ ל-42 יעדים"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"אין"}'::jsonb, 4.1, 0, false),
  ('cel_partner_betterfutureboost5g2000', 'פרטנר', 'cellular', 75, 74.9, 'Better Future Boost 5G 2000GB', '{"נתונים":"2000GB","דקות":"700 דק׳","SMS":"7,000","חו\"ל":"700 דק׳ ל-42 יעדים"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"אין"}'::jsonb, 4.2, 0, false),
  ('cel_partner_king5g800', 'פרטנר', 'cellular', 60, 59.9, 'King 5G 800GB', '{"נתונים":"800GB","דקות":"500 דק׳","SMS":"6,000"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"אין"}'::jsonb, 4.3, 0, false),
  ('cel_partner_boost5g1500', 'פרטנר', 'cellular', 70, 69.9, 'Boost 5G 1500GB', '{"נתונים":"1500GB","דקות":"600 דק׳","SMS":"7,000"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"אין"}'::jsonb, 4.3, 0, false),
  ('cel_pelephone_5g1000', 'פלאפון', 'cellular', 40, 39.9, '5G 1000GB', '{"נתונים":"1000GB","SMS":"5,000","חו\"ל":"מסלול Travel"}'::jsonb, 'regular', 'month', '{}'::jsonb, 3.9, 0, false),
  ('cel_pelephone_4g400', 'פלאפון', 'cellular', 40, 39.9, 'משתלמת דור 4 400GB', '{"נתונים":"400GB","SMS":"3,500","חו\"ל":"מסלול Travel"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.1, 0, false),
  ('cel_pelephone_5gmaxvip2000', 'פלאפון', 'cellular', 50, 49.9, '5G Max VIP All 2000GB', '{"נתונים":"2000GB","SMS":"5,000","חו\"ל":"מסלול Travel"}'::jsonb, 'regular', 'month', '{}'::jsonb, 3.8, 0, false),
  ('cel_golan_300rolling', 'גולן טלקום', 'cellular', 35, 34.9, '300GB מתגלגלת', '{"נתונים":"300GB","דקות":"240 דק׳","חו\"ל":"יש"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.5, 0, false),
  ('cel_golan_400abroad', 'גולן טלקום', 'cellular', 39, null, '400GB חו"ל כלול', '{"נתונים":"400GB","דקות":"100 דק׳","חו\"ל":"1GB חו\"ל לחודש"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.1, 0, false),
  ('cel_golan_750_5g', 'גולן טלקום', 'cellular', 49, null, '750GB דור 5', '{"נתונים":"750GB","דקות":"300 דק׳","חו\"ל":"₪99 הנחה על חבילת חו\"ל"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.5, 0, false),
  ('cel_golan_1500_5g', 'גולן טלקום', 'cellular', 59, null, '1500GB דור 5', '{"נתונים":"1500GB","דקות":"500 דק׳","חו\"ל":"יש"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.2, 0, false),
  ('cel_golan_dataonly500', 'גולן טלקום', 'cellular', 40, null, 'Data Only 500GB', '{"נתונים":"500GB","דקות":"50 דק׳"}'::jsonb, 'dataonly', 'month', '{}'::jsonb, 4.4, 0, false),
  ('cel_golan_550abroad', 'גולן טלקום', 'cellular', 129, null, '550GB החו"ל כלול', '{"נתונים":"550GB","דקות":"500 דק׳","חו\"ל":"חו\"ל כלול"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.4, 0, false),
  ('cel_hotmobile_5gultra2500', 'הוט מובייל', 'cellular', 70, 69.9, '5G Ultra 2500GB', '{"נתונים":"2500GB","דקות":"500 דק׳","SMS":"7,000","חו\"ל":"500 דק׳ ל-27 יעדים"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"חינם"}'::jsonb, 4.1, 0, false),
  ('cel_hotmobile_5gultraplus3000', 'הוט מובייל', 'cellular', 110, 109.9, '5G Ultra Plus Fly', '{"נתונים":"3000GB","דקות":"500 דק׳","SMS":"10,000","חו\"ל":"10GB + 100 דק׳/SMS"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"חינם"}'::jsonb, 4.0, 0, false),
  ('cel_hotmobile_5gultrapremium3000', 'הוט מובייל', 'cellular', 80, 79.9, '5G Ultra Premium', '{"נתונים":"3000GB","דקות":"500 דק׳","SMS":"10,000","חו\"ל":"500 דק׳ ל-27 יעדים"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"חינם"}'::jsonb, 4.1, 0, false),
  ('cel_hotmobile_5ggen2000', 'הוט מובייל', 'cellular', 60, 59.9, '5G Gen 2000GB 2026', '{"נתונים":"2000GB","דקות":"300 דק׳","SMS":"6,000","חו\"ל":"300 דק׳ ל-27 יעדים"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"חינם"}'::jsonb, 3.8, 0, false),
  ('cel_hotmobile_dataonly20', 'הוט מובייל', 'cellular', 11, 10.9, '20GB Data Only', '{"נתונים":"20GB"}'::jsonb, 'dataonly', 'month', '{"SIM":"עד הבית (3 ימי עסקים)"}'::jsonb, 4.1, 0, false),
  ('cel_hotmobile_dataonly150', 'הוט מובייל', 'cellular', 22, 21.9, '150GB Data Only', '{"נתונים":"150GB"}'::jsonb, 'dataonly', 'month', '{"SIM":"עד הבית"}'::jsonb, 3.7, 0, false),
  ('cel_xphone_mechubrim', 'Xphone', 'cellular', 23, 22.5, 'מחוברים', '{"נתונים":"300GB","דקות":"5,000","SMS":"5,000"}'::jsonb, 'regular', 'month', '{"SIM":"₪10","eSIM":"חינם"}'::jsonb, 4.2, 0, false),
  ('cel_xphone_foreverplus', 'Xphone', 'cellular', 30, 29.9, 'Forever Plus', '{"נתונים":"500GB","דקות":"5,000","SMS":"5,000","חו\"ל":"1GB חו\"ל"}'::jsonb, 'regular', 'month', '{"SIM":"₪10","eSIM":"חינם"}'::jsonb, 4.3, 0, false),
  ('cel_xphone_foreverplus5g', 'Xphone', 'cellular', 35, 34.9, 'Forever Plus 5G', '{"נתונים":"500GB","דקות":"5,000","SMS":"5,000","חו\"ל":"1GB חו\"ל"}'::jsonb, 'regular', 'month', '{"SIM":"₪10"}'::jsonb, 4.6, 0, false),
  ('cel_xphone_young50', 'Xphone', 'cellular', 25, 24.9, 'Young 50GB', '{"נתונים":"50GB","דקות":"5,000","SMS":"5,000"}'::jsonb, 'regular', 'month', '{"SIM":"₪10"}'::jsonb, 4.2, 0, false),
  ('cel_xphone_zoberim500', 'Xphone', 'cellular', 30, 29.9, 'צוברים 500GB', '{"נתונים":"500GB (צבירה)","דקות":"5,000","SMS":"5,000","חו\"ל":"1GB צבירה חו\"ל"}'::jsonb, 'regular', 'month', '{"SIM":"₪10"}'::jsonb, 4.5, 0, false),
  ('cel_xphone_zoberim750_5g', 'Xphone', 'cellular', 40, 39.9, 'צוברים 750GB 5G', '{"נתונים":"750GB (5G, צבירה)","דקות":"5,000","SMS":"5,000","חו\"ל":"1GB צבירה חו\"ל"}'::jsonb, 'regular', 'month', '{"SIM":"₪10"}'::jsonb, 4.4, 0, false),
  ('cel_xphone_global3', 'Xphone', 'cellular', 43, 42.9, 'Global 3', '{"נתונים":"ללא הגבלה","דקות":"5,000","SMS":"5,000","חו\"ל":"3GB חו\"ל"}'::jsonb, 'regular', 'month', '{"SIM":"₪10"}'::jsonb, 4.4, 0, false),
  ('cel_xphone_global5', 'Xphone', 'cellular', 49, 48.9, 'Global 5', '{"נתונים":"ללא הגבלה","דקות":"5,000","SMS":"5,000","חו\"ל":"5GB חו\"ל"}'::jsonb, 'regular', 'month', '{"SIM":"₪10"}'::jsonb, 4.6, 0, false),
  ('cel_xphone_global5g', 'Xphone', 'cellular', 55, 54.9, 'Global 5G', '{"נתונים":"ללא הגבלה (5G)","דקות":"5,000","SMS":"5,000","חו\"ל":"5GB חו\"ל"}'::jsonb, 'regular', 'month', '{"SIM":"₪10"}'::jsonb, 4.5, 0, false),
  ('cel_ramilevy_600triple', 'רמי לוי', 'cellular', 35, null, '600GB טריפל', '{"נתונים":"600GB","דקות":"ללא הגבלה","SMS":"5,000"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.4, 0, false),
  ('cel_ramilevy_couple500', 'רמי לוי', 'cellular', 35, null, 'זוג קווים 500GB', '{"נתונים":"500GB","דקות":"ללא הגבלה","SMS":"5,000"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.1, 0, false),
  ('cel_ramilevy_couplepromo250', 'רמי לוי', 'cellular', 30, null, 'מבצע זוגות 250GB', '{"נתונים":"250GB","דקות":"ללא הגבלה","SMS":"2,500"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"חינם"}'::jsonb, 4.5, 0, false),
  ('cel_ramilevy_couple250', 'רמי לוי', 'cellular', 30, null, 'זוג קווים 250GB', '{"נתונים":"250GB","דקות":"ללא הגבלה","SMS":"2,500"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.3, 0, false),
  ('cel_ramilevy_1000xtreme', 'רמי לוי', 'cellular', 55, null, '1000GB Xtreme', '{"נתונים":"1000GB","דקות":"ללא הגבלה","SMS":"2,500"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.4, 0, false),
  ('cel_ramilevy_300xtreme', 'רמי לוי', 'cellular', 35, null, '300GB Xtreme', '{"נתונים":"300GB","דקות":"ללא הגבלה","SMS":"2,500"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.4, 0, false),
  ('cel_ramilevy_500global', 'רמי לוי', 'cellular', 50, null, '500GB Global', '{"נתונים":"500GB","דקות":"ללא הגבלה","SMS":"2,500","חו\"ל":"500 דק׳ ליעדים בחו\"ל"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.3, 0, false),
  ('cel_ramilevy_maxkasher', 'רמי לוי', 'cellular', 17, 16.9, 'Max כשר', '{"דקות":"10,000 ברשת / 5,000 מחוץ"}'::jsonb, 'kosher', 'month', '{}'::jsonb, 4.4, 0, false),
  ('cel_ramilevy_zolkasher', 'רמי לוי', 'cellular', 15, 14.9, 'זול להיות בקשר כשר', '{"דקות":"10,000 ברשת / 4,000 מחוץ"}'::jsonb, 'kosher', 'month', '{}'::jsonb, 4.5, 0, false),
  ('cel_wecom_family', 'WeCom', 'cellular', 30, 29.9, 'We Are Family', '{"נתונים":"גלישה חופשית (דור 4)","דקות":"5,000","SMS":"3,000"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"חינם"}'::jsonb, 4.1, 0, false),
  ('cel_wecom_basic150', 'WeCom', 'cellular', 33, 32.9, 'Basic 150GB', '{"נתונים":"150GB","דקות":"3,000","SMS":"3,000"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"חינם"}'::jsonb, 4.0, 0, false),
  ('cel_wecom_free5g', 'WeCom', 'cellular', 35, null, 'Free 5G', '{"נתונים":"גלישה חופשית (5G)","דקות":"5,000","SMS":"3,000"}'::jsonb, 'regular', 'month', '{"דמי חיבור":"חינם"}'::jsonb, 4.3, 0, false),
  ('cel_wecom_global5g', 'WeCom', 'cellular', 60, 59.9, 'Global 5G', '{"נתונים":"גלישה חופשית (5G)","דקות":"3,000","SMS":"3,000","חו\"ל":"5GB חו\"ל לחודש + תעריף מוזל"}'::jsonb, 'regular', 'month', '{"הצטרפות":"₪79.90 חד-פעמי"}'::jsonb, 4.0, 0, false),
  ('cel_019mobile_bigdata300', '019 מובייל', 'cellular', 40, 39.9, 'Big Data 300GB', '{"נתונים":"300GB","דקות":"5,000","SMS":"5,000"}'::jsonb, 'regular', 'month', '{"SIM":"₪10","eSIM":"חינם"}'::jsonb, 4.0, 0, false),
  ('cel_019mobile_lifetime12', '019 מובייל', 'cellular', 20, 19.8, 'לכל החיים 12GB', '{"נתונים":"12GB","דקות":"5,000","SMS":"5,000"}'::jsonb, 'regular', 'month', '{"SIM":"₪10","eSIM":"חינם"}'::jsonb, 4.2, 0, false),
  ('cel_019mobile_bulbpony30', '019 מובייל', 'cellular', 22, 21.9, 'בול בפוני 30GB', '{"נתונים":"30GB","דקות":"5,000","SMS":"5,000"}'::jsonb, 'regular', 'month', '{"SIM":"₪10"}'::jsonb, 4.4, 0, false),
  ('cel_019mobile_gazamnu170', '019 מובייל', 'cellular', 26, 25.9, 'הגזמנו 170GB', '{"נתונים":"170GB","דקות":"5,000","SMS":"5,000"}'::jsonb, 'regular', 'month', '{"SIM":"₪10"}'::jsonb, 4.2, 0, false),
  ('cel_019mobile_weit100', '019 מובייל', 'cellular', 30, 29.9, 'We It 100GB', '{"נתונים":"100GB","דקות":"5,000","SMS":"5,000","חו\"ל":"100 דק׳ למבחר מדינות"}'::jsonb, 'regular', 'month', '{"SIM":"₪10"}'::jsonb, 4.2, 0, false),
  ('cel_019mobile_bigtime200', '019 מובייל', 'cellular', 32, 31.8, 'Big Time 200GB', '{"נתונים":"200GB","דקות":"5,000","SMS":"5,000","חו\"ל":"200 דק׳ למבחר מדינות"}'::jsonb, 'regular', 'month', '{"SIM":"₪10"}'::jsonb, 4.2, 0, false),
  ('cel_019mobile_simdata2', '019 מובייל', 'cellular', 12, null, 'SIM Data 2GB', '{"נתונים":"2GB"}'::jsonb, 'dataonly', 'month', '{"SIM":"₪10"}'::jsonb, 4.4, 0, false),
  ('cel_019mobile_netfree_s_kasher', '019 מובייל', 'cellular', 25, null, 'נטפרי S 10GB כשר', '{"נתונים":"10GB"}'::jsonb, 'kosher', 'month', '{"SIM":"₪10 + תשלום נטפרי"}'::jsonb, 4.0, 0, false),
  ('cel_019mobile_netfree_m_kasher', '019 מובייל', 'cellular', 42, null, 'נטפרי M 40GB כשר', '{"נתונים":"40GB"}'::jsonb, 'kosher', 'month', '{"SIM":"₪10 + תשלום נטפרי"}'::jsonb, 4.0, 0, false),
  ('cel_walla_5g400', 'וואלה מובייל', 'cellular', 40, 39.9, 'WallaPower 5G 400GB', '{"נתונים":"400GB","חו\"ל":"שיחות לחו\"ל כלולות"}'::jsonb, 'regular', 'month', '{}'::jsonb, 3.9, 0, false),
  ('cel_walla_family300', 'וואלה מובייל', 'cellular', 75, null, 'WallaFamily 300GB', '{"נתונים":"300GB","חו\"ל":"שיחות חו\"ל כלולות"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.1, 0, false),
  ('cel_walla_basic300', 'וואלה מובייל', 'cellular', 31, 30.9, 'WallaBasic 300GB', '{"נתונים":"300GB","חו\"ל":"שיחות חו\"ל כלולות"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.2, 0, false),
  ('net_bezeq_bfiber300', 'בזק', 'internet', 109, null, 'bFiber 300 מגה', '{"מהירות":"עד 300/100"}'::jsonb, 'regular', 'month', '{"התקנה":"סיבים חינם אם קיימת תשתית; דירה ₪199 / צמוד קרקע ₪499"}'::jsonb, 4.0, 0, false),
  ('net_bezeq_bfiber1g', 'בזק', 'internet', 99, null, 'bFiber 1 ג׳יגה', '{"מהירות":"עד 1000/100"}'::jsonb, 'regular', 'month', '{"התקנה":"סיבים חינם אם קיימת תשתית; דירה ₪199 / צמוד קרקע ₪499"}'::jsonb, 4.2, 0, false),
  ('net_bezeq_bfiber1g250up', 'בזק', 'internet', 149, null, 'bFiber 250up / 1 ג׳יגה', '{"מהירות":"עד 1000/250"}'::jsonb, 'regular', 'month', '{"התקנה":"סיבים חינם אם קיימת תשתית; דירה ₪199 / צמוד קרקע ₪499"}'::jsonb, 4.1, 0, false),
  ('net_bezeq_bfiber25g', 'בזק', 'internet', 125, null, 'bFiber 2.5 ג׳יגה', '{"מהירות":"עד 2500/250"}'::jsonb, 'regular', 'month', '{"התקנה":"סיבים חינם אם קיימת תשתית; דירה ₪199 / צמוד קרקע ₪499"}'::jsonb, 3.9, 0, false),
  ('net_bezeq_bfiber5g', 'בזק', 'internet', 179, null, 'Multi bFiber 5 ג׳יגה', '{"מהירות":"עד 5000/500","נתב":"+₪39.9/ח׳"}'::jsonb, 'regular', 'month', '{"התקנה":"סיבים חינם אם קיימת תשתית; דירה ₪199 / צמוד קרקע ₪499"}'::jsonb, 4.1, 0, false),
  ('net_bezeq_copper100', 'בזק', 'internet', 65, null, 'אינטרנט 100 מגה (נחושת)', '{"מהירות":"עד 100/3","נתב":"+₪21.9/ח׳"}'::jsonb, 'regular', 'month', '{"התקנה":"₪49"}'::jsonb, 3.9, 0, false),
  ('net_bezeq_copper100_10up', 'בזק', 'internet', 99, null, 'אינטרנט 100/10up (נחושת)', '{"מהירות":"עד 100/10","נתב":"+₪21.9/ח׳"}'::jsonb, 'regular', 'month', '{"התקנה":"₪49"}'::jsonb, 3.9, 0, false),
  ('net_bezeq_copper200', 'בזק', 'internet', 109, null, 'אינטרנט 200 מגה (נחושת)', '{"מהירות":"עד 200/20","נתב":"+₪21.9/ח׳"}'::jsonb, 'regular', 'month', '{"התקנה":"₪49"}'::jsonb, 4.0, 0, false),
  ('net_hot_fiber600ai', 'HOT', 'internet', 99, null, 'אינטרנט 600Mb Fiber AI', '{"מהירות":"עד 600/100","נתב":"מגדיל טווח מתקדם + נקודת רשת כלולים"}'::jsonb, 'regular', 'month', '{"התקנה":"חינם בדירה; בית פרטי ₪499; ציוד עצמי -₪40"}'::jsonb, 3.7, 0, false),
  ('net_hot_fiber1g_hbomax', 'HOT', 'internet', 109, null, 'אינטרנט 1000Mb Fiber AI + HBO Max', '{"מהירות":"עד 1000/100","נתב":"מגדיל טווח + נקודת רשת כלולים"}'::jsonb, 'regular', 'month', '{"התקנה":"חינם בדירה; בית פרטי ₪499"}'::jsonb, 3.8, 0, false),
  ('net_hot_homeplus1g', 'HOT', 'internet', 124, null, 'Home Plus 1000Mb', '{"מהירות":"עד 1000/100","נתב":"2 מגדילי טווח + 2 נקודות רשת כלולים"}'::jsonb, 'regular', 'month', '{"התקנה":"חינם בדירה; בית פרטי ₪499"}'::jsonb, 4.0, 0, false),
  ('net_cellcom_fiber1g', 'סלקום', 'internet', 119, null, 'Fiber 1GB', '{"מהירות":"עד 1000/100","נתב":"כלול"}'::jsonb, 'regular', 'month', '{}'::jsonb, 3.8, 0, false),
  ('net_cellcom_fiber25g', 'סלקום', 'internet', 99, null, 'Fiber 2.5GB', '{"מהירות":"עד 2500/250","נתב":"Star Mesh WiFi7 כלול (+₪29.9 אופציה)"}'::jsonb, 'regular', 'month', '{}'::jsonb, 3.9, 0, false),
  ('net_partner_fiber600', 'פרטנר', 'internet', 69, null, 'Fiber 600Mb', '{"מהירות":"עד 600/100","נתב":"WiFi7 +₪25/ח׳"}'::jsonb, 'regular', 'month', '{"התקנה":"חינם בבניין; 1-4 דירות ₪499 (36 תשלומים)"}'::jsonb, 4.2, 0, false),
  ('net_partner_fiber1g', 'פרטנר', 'internet', 39, null, 'Fiber 1000Mb', '{"מהירות":"עד 1000/100","נתב":"WiFi7 כלול"}'::jsonb, 'regular', 'month', '{"התקנה":"חינם בבניין 5+ דירות; 1-4 דירות ₪499"}'::jsonb, 4.1, 0, false),
  ('net_partner_fiber25g', 'פרטנר', 'internet', 149, null, 'Fiber 2500Mb', '{"מהירות":"עד 2500/250","נתב":"כלול"}'::jsonb, 'regular', 'month', '{"התקנה":"חינם בבניין; בית פרטי ₪499"}'::jsonb, 4.3, 0, false),
  ('net_golan_fiber1g', 'גולן טלקום', 'internet', 89, null, 'אינטרנט סיבים משתלם', '{"מהירות":"עד 1000/100","נתב":"+₪25/ח׳"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.4, 0, false),
  ('net_xphone_300mb', 'Xphone', 'internet', 100, 99.99, 'אינטרנט ביתי 300Mb', '{"מהירות":"עד 300/100"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.5, 0, false),
  ('net_xphone_500mb', 'Xphone', 'internet', 100, 99.99, 'אינטרנט ביתי 500Mb', '{"מהירות":"עד 500/50"}'::jsonb, 'regular', 'month', '{"התקנה":"עלות מוזלת"}'::jsonb, 4.2, 0, false),
  ('net_xphone_1000mb', 'Xphone', 'internet', 122, null, 'אינטרנט ביתי 1000Mb', '{"מהירות":"עד 1000/100"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.6, 0, false),
  ('net_xphone_200mb', 'Xphone', 'internet', 100, 99.99, 'אינטרנט ביתי 200Mb', '{"מהירות":"עד 200/20"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.4, 0, false),
  ('net_gilat_1g_online', 'גילת', 'internet', 49, null, '1GB מבצע אונליין', '{"מהירות":"עד 1000/100","נתב":"כלול (WiFi7 +₪10/ח׳)"}'::jsonb, 'regular', 'month', '{"התקנה":"הסבה: דירה ₪49 / פרטי ₪99-149; חדש: דירה ₪199 / פרטי ₪199-499"}'::jsonb, 4.6, 0, false),
  ('net_gilat_1g_year', 'גילת', 'internet', 79, null, '1GB שנה', '{"מהירות":"עד 1000/100","נתב":"כלול (WiFi7 +₪10/ח׳)"}'::jsonb, 'regular', 'month', '{"התקנה":"הסבה: דירה ₪49 / פרטי ₪99-149; חדש: דירה ₪199 / פרטי ₪199-499"}'::jsonb, 4.3, 0, false),
  ('net_gilat_1g_lifetime', 'גילת', 'internet', 95, null, '1GB לכל החיים', '{"מהירות":"עד 1000/100","נתב":"כלול (WiFi7 +₪10/ח׳)"}'::jsonb, 'regular', 'month', '{"התקנה":"הסבה: דירה ₪49 / פרטי ₪99-149; חדש: דירה ₪199 / פרטי ₪199-499"}'::jsonb, 4.3, 0, false),
  ('net_ccc_fiber300', 'CCC', 'internet', 90, null, 'פייבר 300 מגה', '{"מהירות":"עד 300Mb"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.1, 0, false),
  ('net_ccc_fiber500', 'CCC', 'internet', 95, null, 'פייבר 500 מגה', '{"מהירות":"עד 500Mb"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.3, 0, false),
  ('net_ccc_fiber1g', 'CCC', 'internet', 100, null, 'פייבר 1000 מגה', '{"מהירות":"עד 1000Mb"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.2, 0, false),
  ('net_ccc_copper40', 'CCC', 'internet', 80, null, 'דאבל 40 מגה (נחושת)', '{"מהירות":"עד 40Mb"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.3, 0, false),
  ('net_ccc_copper100', 'CCC', 'internet', 85, null, 'דאבל 100 מגה (נחושת)', '{"מהירות":"עד 100Mb"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.3, 0, false),
  ('net_ccc_copper200', 'CCC', 'internet', 95, null, 'דאבל 200 מגה (נחושת)', '{"מהירות":"עד 200Mb"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.4, 0, false),
  ('tv_hot_rak-televizia', 'HOT', 'tv', 89, null, 'רק טלוויזיה', '{"ערוצים":"~140"}'::jsonb, 'regular', 'month', '{}'::jsonb, 3.7, 0, false),
  ('tv_hot_sport', 'HOT', 'tv', 99, null, 'רק טלוויזיה + ספורט', '{"ערוצים":"~140","ממירים":"1"}'::jsonb, 'regular', 'month', '{}'::jsonb, 3.9, 0, false),
  ('tv_partner_sport', 'פרטנר', 'tv', 95, null, 'Partner TV + ספורט', '{"ערוצים":"~100","ממירים":"1","VOD":"30,000+"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.3, 0, false),
  ('tv_cellcom_netflix', 'סלקום', 'tv', 69, null, 'סלקום TV + Netflix', '{"ערוצים":"~85","ממירים":"1","VOD":"30,000"}'::jsonb, 'regular', 'month', '{}'::jsonb, 3.9, 0, false),
  ('tv_stingtv_hbo-max-standard', 'STING TV', 'tv', 49, null, 'HBO Max Standard', '{"ערוצים":"~70","ממירים":"1","VOD":"40,000+"}'::jsonb, 'regular', 'month', '{"התקנה":"מהיום להיום (לא כולל בית פרטי)"}'::jsonb, 3.9, 0, false),
  ('tv_stingtv_disney-plus', 'STING TV', 'tv', 49, null, 'דיסני+', '{"ערוצים":"~70"}'::jsonb, 'regular', 'month', '{"התקנה":"מהיום להיום"}'::jsonb, 4.0, 0, false),
  ('tv_stingtv_mibeit-yes', 'STING TV', 'tv', 49, null, 'מבית yes', '{"ערוצים":"~70","VOD":"40,000"}'::jsonb, 'regular', 'month', '{"התקנה":"מהיום להיום"}'::jsonb, 4.3, 0, false),
  ('tv_yes_sting-plus-by-yes', 'yes', 'tv', 49, null, 'Sting+ by yes', '{"ערוצים":"~70","ממירים":"1","VOD":"40,000"}'::jsonb, 'regular', 'month', '{"התקנה":"מהיום להיום"}'::jsonb, 4.2, 0, false),
  ('tv_nexttv_app', 'NextTV', 'tv', 70, 69.9, 'אפליקציית Next TV', '{"VOD":"~40,000"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.0, 0, false),
  ('tri_hot_triple-hbo-max', 'HOT', 'triple', 199, null, 'טריפל HBO Max', '{"ערוצים":"~140","מהירות":"עד 1000","סטרימרים":"2"}'::jsonb, 'regular', 'month', '{"התקנה":"חינם בדירה / בית פרטי ₪499"}'::jsonb, 3.9, 0, false),
  ('tri_hot_triple-mondial-1000', 'HOT', 'triple', 169, null, 'טריפל מונדיאל עד 1000Mb', '{"ערוצים":"~140","מהירות":"עד 1000","ממירים":"2"}'::jsonb, 'regular', 'month', '{"התקנה":"חינם בדירה / בית פרטי ₪499"}'::jsonb, 4.0, 0, false),
  ('tri_cellcom_triple-1gb-mondial-projector', 'סלקום', 'triple', 159, null, 'טריפל 1GB מונדיאל (מקרן)', '{"מהירות":"עד 1000","ממירים":"3"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.2, 0, false),
  ('tri_cellcom_triple-1gb-mondial-screen', 'סלקום', 'triple', 189, null, 'טריפל 1GB מונדיאל (מסך)', '{"מהירות":"עד 1000","ממירים":"3"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.1, 0, false),
  ('tri_cellcom_triple-2-5gb', 'סלקום', 'triple', 179, null, 'טריפל 2.5GB', '{"מהירות":"עד 2500","ממירים":"2"}'::jsonb, 'regular', 'month', '{}'::jsonb, 3.8, 0, false),
  ('tri_stingtv_sting-fiber-hbo-max', 'STING TV', 'triple', 149, null, 'Sting+Fiber HBO Max', '{"ערוצים":"~70","מהירות":"עד 1000","ממירים":"2"}'::jsonb, 'regular', 'month', '{"התקנה":"בית פרטי ₪499"}'::jsonb, 3.9, 0, false),
  ('tri_yes_yes-fiber-triple', 'yes', 'triple', 209, null, 'yes+Fiber הטריפל', '{"ערוצים":"160+","מהירות":"עד 1000","ממירים":"2"}'::jsonb, 'regular', 'month', '{"התקנה":"בית פרטי ₪499"}'::jsonb, 4.0, 0, false),
  ('tri_yes_sting-fiber-by-yes', 'yes', 'triple', 149, null, 'Sting+Fiber by yes', '{"ערוצים":"~70","מהירות":"עד 1000","ממירים":"2"}'::jsonb, 'regular', 'month', '{"התקנה":"בית פרטי ₪499"}'::jsonb, 3.9, 0, false),
  ('tri_nexttv_fiber-tv-1gb', 'NextTV', 'triple', 119, null, 'אינטרנט סיבים + TV 1GB', '{"מהירות":"עד 1000"}'::jsonb, 'regular', 'month', '{"התקנה":"חינם"}'::jsonb, 4.3, 0, false),
  ('tri_nexttv_fiber-tv-2gb', 'NextTV', 'triple', 164, null, 'אינטרנט סיבים + TV 2GB', '{"מהירות":"עד 2000"}'::jsonb, 'regular', 'month', '{}'::jsonb, 3.9, 0, false),
  ('tri_golan_triple-hamushalam', 'גולן טלקום', 'triple', 139, null, 'טריפל המושלם', '{"מהירות":"עד 1000/100"}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.2, 0, false),
  ('ab_019', '019 מובייל', 'abroad', 1, null, 'תעריף לדקה — אירופה', '{}'::jsonb, 'regular', 'minute', '{}'::jsonb, 3.9, 0, false),
  ('ab_golan', 'גולן טלקום', 'abroad', 10, null, '₪9.90/יום — כל אירופה', '{}'::jsonb, 'regular', 'day', '{}'::jsonb, 4.2, 0, false),
  ('ab_partner', 'פרטנר', 'abroad', 29, null, 'World Pack 1GB חודשי', '{}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.1, 0, true),
  ('ab_pelephone', 'פלאפון', 'abroad', 49, null, 'World 5GB חודשי', '{}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.3, 0, false),
  ('ab_airalo', 'Airalo eSIM', 'abroad', 25, null, 'eSIM אירופה 10GB', '{}'::jsonb, 'regular', 'package', '{}'::jsonb, 4.5, 0, false),
  ('ab_airalo_3g', 'Airalo eSIM', 'abroad', 13, null, 'eSIM אירופה 3GB', '{}'::jsonb, 'regular', 'package', '{}'::jsonb, 4.5, 0, true),
  ('ab_airalo_global', 'Airalo eSIM', 'abroad', 37, null, 'eSIM גלובל 5GB', '{}'::jsonb, 'regular', 'package', '{}'::jsonb, 4.4, 0, false),
  ('ab_hot', 'הוט מובייל', 'abroad', 9, null, '₪8.90/יום — אירופה', '{}'::jsonb, 'regular', 'day', '{}'::jsonb, 4.0, 0, false),
  ('ab_partner_3g', 'פרטנר', 'abroad', 49, null, 'World Pack 3GB חודשי', '{}'::jsonb, 'regular', 'month', '{}'::jsonb, 4.2, 0, true),
  ('ab_cellcom', 'סלקום', 'abroad', 8, null, '₪7.90/יום — כל אירופה', '{}'::jsonb, 'regular', 'day', '{}'::jsonb, 4.1, 0, false),
  ('ab_019_world', '019 מובייל', 'abroad', 19, null, '2GB גלישה חודשי', '{}'::jsonb, 'regular', 'month', '{}'::jsonb, 3.8, 0, false)
on conflict (id) do update set
  provider      = excluded.provider,
  category      = excluded.category,
  price         = excluded.price,
  price_exact   = excluded.price_exact,
  title         = excluded.title,
  specs         = excluded.specs,
  kind          = excluded.kind,
  price_unit    = excluded.price_unit,
  fees          = excluded.fees,
  rating        = excluded.rating,
  review_count  = excluded.review_count,
  is_featured   = excluded.is_featured,
  updated_at    = now();
